#!/bin/sh
set -e

package="bash-minos-settings"
package_dir="/usr/share/minos/${package}"
diverge_dir="${package_dir}/diverge"

users="$(cat /etc/passwd | awk -F: '{if ($3 >= 1000 && $3 < 60000) print $1}')"

_diverge_element() {
    _diverge__orig="${1}"
    _diverge__new="${2}"
    _diverge__backup="$(printf "%s\\n" "${_diverge__orig}" | busybox sed 's:/:##:g')"

    if ! LC_ALL=C dpkg-divert --list "${package}" | \
        grep -xFq "diversion of ${_diverge__orig} to ${diverge_dir}/${_diverge__backup} by ${package}"; then
        #busybox grep don't support the -x flag in old releases
        busybox mkdir -p "${diverge_dir}"
        dpkg-divert --package "${package}" --rename --add \
            --divert "${diverge_dir}/${_diverge__backup}" "${_diverge__orig}"

        busybox ln -s "${_diverge__new}" "${_diverge__orig}" || :
    fi
}

_install_element_system_users() {
    test -e "${1}" || return 1
    for user in ${users}; do
        su "${user}" -c "test -f ~/.minos/not_override" && continue

        if su "${user}" -c "test -e ${2}"; then
            if su "${user}" -c "busybox diff -q ${1} ${2}" >/dev/null; then
            #dist_size="$(su "${user}" -c "busybox du -sL ${1}"|busybox cut -f1)"
            #user_size="$(su "${user}" -c "busybox du -sL ${2}"|busybox cut -f1)"
            #if [ X"${dist_size}" = X"${user_size}" ]; then
                continue
            else
                vdotfile="minos-backup.$(busybox date +"%d-%m-%Y-%H:%M")"
                printf "%s\\n" "${package}: old $user's ${2} archive found, replacing and creating backup to ${2}.${vdotfile}"
                su "${user}" -c "busybox mv ${2} ${2}.${vdotfile}"
                su "${user}" -c "busybox cp -rL ${1} ${2}"
            fi
        else
            su "${user}" -c "busybox mkdir -p $(busybox dirname "${2}")"
            su "${user}" -c "busybox cp -rL ${1} ${2}"
        fi
    done
}

case "${1}" in
    configure|abort-remove)
        _diverge_element /etc/bash.bashrc  "${package_dir}/etc##bash.bashrc"
        _diverge_element /etc/inputrc      "${package_dir}/etc##inputrc"
        _diverge_element /etc/skel/.bashrc "${package_dir}/etc##skel##.bashrc"
        _install_element_system_users      '/etc/skel/.bashrc' '~/.bashrc'
        ;;
esac

#DEBHELPER#
exit 0
