#!/bin/sh
set -e

package="bash-minos-settings"
diverge_dir="/usr/share/minos/diverge"

_diverge_element() {
    _diverge__orig="${1}"
    _diverge__new="${2}"
    _diverge__backup="$(printf "%s" "${_diverge__orig}" | sed 's:/:##:g')"

    if ! LC_ALL=C dpkg-divert --list "${package}" | \
        grep -xFq "diversion of ${_diverge__orig} to ${diverge_dir}/${_diverge__backup} by ${package}"; then
        mkdir -p "${diverge_dir}"
        dpkg-divert --package "${package}" --add --rename \
            --divert "${diverge_dir}/${_diverge__backup}" "${_diverge__orig}"
        ln -s "${_diverge__new}" "${_diverge__orig}"
    fi
}

_undiverge_element() {
    _diverge__orig="${1}"
    _diverge__new="${2}"
    _diverge__backup="$(printf "%s" "${_diverge__orig}" | sed 's:/:##:g')"

    if LC_ALL=C dpkg-divert --list "${package}" | \
        grep -xFq "diversion of ${_diverge__orig} to ${diverge_dir}/${_diverge__backup} by ${package}"; then
        rm -rf "${_diverge__orig}"
        dpkg-divert --package "${package}" --rename --remove "${_diverge__orig}"
        rmdir "${diverge_dir}" 2>/dev/null || :
    fi
}

_replace_file_on_system_users() {
    for user in ${users}; do
        su "${user}" -c "test -f ~/.minos/not_override" && continue

        if su "${user}" -c "test -f ${2}" || su "${user}" -c "test -d ${2}"; then
            dist_size="$(su "${user}" -c "du -s ${1}"|cut -f1)"
            user_size="$(su "${user}" -c "du -s ${2}"|cut -f1)"
            vdotfile="minos-backup.$(date +"%d-%m-%Y-%H:%M")"
            if [ X"${dist_size}" = X"${user_size}" ]; then
                continue
            else
                printf "%s\\n" "minos-core-settings: old ${user}'s ${2} archive found, replacing and creating backup to ${2}.${vdotfile}"
                su "${user}" -c "mv ${2} ${2}.${vdotfile}"
                su "${user}" -c "cp -rL ${1} ${2}"
            fi
        else
            su "${user}" -c "cp -rL ${1} ${2}"
        fi
    done
}

if [ "${1}" = "remove" ] || [ "${1}" = "deconfigure" ]; then
    _undiverge_element /etc/bash.bashrc  /usr/share/minos/bash.bashrc
    _undiverge_element /etc/inputrc      /usr/share/minos/inputrc
    _undiverge_element /etc/skel/.bashrc /usr/share/minos/skel/.bashrc
fi

#DEBHELPER#
